cmake_minimum_required(VERSION 3.19)
project(ManagedMetadataTests LANGUAGES CXX ASM)
get_filename_component(RUNTIME "${CMAKE_CURRENT_SOURCE_DIR}/../../.." ABSOLUTE)
if(NOT GCV2_RUNTIME_LIB_DIR OR NOT PRODUCT_BUILD)
    message(FATAL_ERROR "Explicit product library and build directories required")
endif()
add_executable(metadata main.cpp ../test_empty_stackmap.cpp)
if(WIN32)
    target_sources(metadata PRIVATE windows_input.S)
endif()
target_include_directories(metadata PRIVATE .. ${RUNTIME}/src ${RUNTIME}/include
    ${RUNTIME}/src/Loader/BinaryFile ${RUNTIME}/src/Heap
    ${PRODUCT_BUILD}/src/Heap ${PRODUCT_BUILD}/src/Heap/Allocator)
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    target_include_directories(metadata PRIVATE ${RUNTIME}/src/Heap/z/os/linux)
    target_link_options(metadata PRIVATE -Wl,--exclude-libs,ALL)
endif()
target_compile_features(metadata PRIVATE cxx_std_17)
target_compile_options(metadata PRIVATE -fno-rtti -fexceptions -fvisibility-inlines-hidden)
target_compile_definitions(metadata PRIVATE MRT_TESTABLE_INTERNALS=1 MRT_GC_UNIT_TESTS=1
    MRT_PRODUCT_TESTABLE_INTERNALS=1)
target_link_directories(metadata PRIVATE ${GCV2_RUNTIME_LIB_DIR})
target_link_libraries(metadata PRIVATE cangjie-runtime boundscheck)
set_target_properties(metadata PROPERTIES BUILD_RPATH "${GCV2_RUNTIME_LIB_DIR}")
