/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package std.ast

import std.collection.ArrayList

public func parsePattern(input: Tokens): Pattern {
    /* Get node info from flatbuffer */
    let node = unsafe {
        try {
            parse(input, {
                p: CPointer<UInt8> => return CJ_AST_ParsePattern(match (MACRO_OBJECT.get()) {
                    case Some(ptr) => ptr
                    case None => CPointer<Unit>()
                }, p, CPointer<Int64>())
            })
        } catch (e: Exception) {
            throw ParseASTException("Failed to parse pattern.")
        }
    }
    /* Get decl info from flatbuffer */
    var astNode = generatePatternAST(node.GetRootAsPattern())
    return astNode
}

public func parsePatternFragment(input: Tokens, startFrom!: Int64 = 0): (Pattern, Int64) {
    let (node, count) = unsafe {
        try {
            parseFragment(
                input,
                startFrom,
                {
                    p: CPointer<UInt8>, sizeRef: CPointer<Int64> => return CJ_AST_ParsePattern(
                        match (MACRO_OBJECT.get()) {
                            case Some(ptr) => ptr
                            case None => CPointer<Unit>()
                        }, p, sizeRef)
                }
            )
        } catch (e: Exception) {
            throw ParseASTException("Failed to parse pattern fragment.")
        }
    }
    var astNode = generatePatternAST(node.GetRootAsPattern())
    return (astNode, count)
}

func generatePatternAST(patternNode: Option<ASTFormat_Pattern>): Pattern {
    var pattern = match (patternNode) {
        case Some(v) => v
        case None => throw ParseASTException("Failed to get the pattern node.")
    }
    var nodeBase = match (pattern.GetBase()) {
        case Some(v) => v
        case None => throw ParseASTException("Pattern node has no base information.")
    }
    var astKind: String = nodeBase.GetAstKind()
    var astNode = match (astKind) {
        case "var_pattern" => createVarPattern(pattern)
        case "const_pattern" => createConstPattern(pattern)
        case "tuple_pattern" => createTuplePattern(pattern)
        case "enum_pattern" => createEnumPattern(pattern)
        case "var_or_enum_pattern" => createVarOrEnumPattern(pattern, nodeBase.GetBegin())
        case "type_pattern" => createTypePattern(pattern)
        case "except_type_pattern" => createExceptTypePattern(pattern)
        case "effect_type_pattern" => createCommandTypePattern(pattern)
        case "wildcard_pattern" => createWildcardPattern(pattern, nodeBase.GetBegin())
        case _ => throw ParseASTException("Unsupported pattern node kind: '${astKind}'.")
    }
    addPositionInfo(astNode, nodeBase)
    return astNode
}

func createVarPattern(pattern: ASTFormat_Pattern): VarPattern {
    var varPattern = match (pattern.GetPatternAsVarPattern()) {
        case Some(v) => v
        case None => throw ParseASTException("Failed to get the var pattern.")
    }
    var varDecl = match (varPattern.GetVarDecl()) {
        case Some(v) => v
        case None => throw ParseASTException("Failed to get the var declaration.")
    }
    var declBase = match (varDecl.GetBase()) {
        case Some(v) => v
        case None => throw ParseASTException("Failed to get the base of the var declaration.")
    }
    var indentifier = Token(TokenKind.IDENTIFIER, declBase.GetIdentifier()).addPosition(declBase.GetIdentifierPos())
    return VarPattern(indentifier)
}

func createConstPattern(pattern: ASTFormat_Pattern): ConstPattern {
    var constPattern = match (pattern.GetPatternAsConstPattern()) {
        case Some(v) => v
        case None => throw ParseASTException("Failed to get the constant pattern.")
    }
    var exprNode = generateExprAST(constPattern.GetLiteral())
    var litConstExpr = match (exprNode as LitConstExpr) {
        case Some(v) => v
        case None => throw ParseASTException("Failed to get the constant literal expression.")
    }
    return ConstPattern(litConstExpr)
}

func createWildcardPattern(_: ASTFormat_Pattern, pos: ASTFormat_Position): WildcardPattern {
    var keyWord = Tokens().append(Token(TokenKind.WILDCARD).addPosition(pos))
    return WildcardPattern(keyWord)
}

func createVarOrEnumPattern(pattern: ASTFormat_Pattern, pos: ASTFormat_Position): VarOrEnumPattern {
    var varOrEnumPattern = match (pattern.GetPatternAsVarOrEnumPattern()) {
        case Some(v) => v
        case None => throw ParseASTException("Failed to get the var or enum pattern.")
    }
    var identifier = Token(TokenKind.IDENTIFIER, varOrEnumPattern.GetIdentifier()).addPosition(pos)
    /* Need to support? generatePatternAST(varOrEnumPattern.GetPattern()) */
    return VarOrEnumPattern(identifier)
}

func createExceptTypePattern(pattern: ASTFormat_Pattern): ExceptTypePattern {
    var exceptTypePattern = match (pattern.GetPatternAsExceptTypePattern()) {
        case Some(v) => v
        case None => throw ParseASTException("Failed to get the except type pattern.")
    }
    var p = generatePatternAST(exceptTypePattern.GetPattern())
    var colon: Token = Token(TokenKind.COLON).addPosition(exceptTypePattern.GetColonPos())
    let typeSrc = exceptTypePattern.GetTypes()
    var types: ArrayList<TypeNode> = ArrayList<TypeNode>(typeSrc.size, {i => generateTypeAST(typeSrc[i])})
    var bitOr = Tokens()
    for (pos in exceptTypePattern.GetBitOrPosVec()) {
        bitOr.append(Token(TokenKind.BITOR).addPosition(pos))
    }
    return ExceptTypePattern(p, colon, types, bitOr)
}

func createCommandTypePattern(pattern: ASTFormat_Pattern): CommandTypePattern {
    var commandTypePattern = match (pattern.GetPatternAsCommandTypePattern()) {
        case Some(v) => v
        case None => throw ParseASTException("Failed to get the command type pattern.")
    }
    var p = generatePatternAST(commandTypePattern.GetPattern())
    var colon: Token = Token(TokenKind.COLON).addPosition(commandTypePattern.GetColonPos())
    let typeSrc = commandTypePattern.GetTypes()
    var types: ArrayList<TypeNode> = ArrayList<TypeNode>(typeSrc.size, {i => generateTypeAST(typeSrc[i])})
    var bitOr = Tokens()
    for (pos in commandTypePattern.GetBitOrPosVec()) {
        bitOr.append(Token(TokenKind.BITOR).addPosition(pos))
    }
    return CommandTypePattern(p, colon, types, bitOr)
}

func createTypePattern(pattern: ASTFormat_Pattern): TypePattern {
    var typePattern = match (pattern.GetPatternAsTypePattern()) {
        case Some(v) => v
        case None => throw ParseASTException("Failed to get the type pattern.")
    }
    var p = generatePatternAST(typePattern.GetPattern())
    var colon: Token = Token(TokenKind.COLON).addPosition(typePattern.GetColonPos())
    var ty: TypeNode = generateTypeAST(typePattern.GetType())
    return TypePattern(p, colon, ty)
}

func createEnumPattern(pattern: ASTFormat_Pattern): EnumPattern {
    var enumPattern = match (pattern.GetPatternAsEnumPattern()) {
        case Some(v) => v
        case None => throw ParseASTException("Failed to get the enum pattern.")
    }
    var exprNode = match (enumPattern.GetRef()) {
        case Some(v) => generateExprAST(v)
        case None => throw ParseASTException("Constructor of 'EnumPattern' is not a 'RefExpr'.")
    }
    var lParen: Token = Token(TokenKind.LPAREN).addPosition(enumPattern.GetLeftParenPos())
    let patSrc = enumPattern.GetPatterns()
    var patterns: ArrayList<Pattern> = ArrayList<Pattern>(patSrc.size, {i => generatePatternAST(patSrc[i])})
    let commas = Tokens()
    for (commaPos in enumPattern.GetCommaPosVec()) {
        commas.append(Token(TokenKind.COMMA).addPosition(commaPos))
    }
    var rParen: Token = Token(TokenKind.RPAREN).addPosition(enumPattern.GetRightParenPos())
    return EnumPattern(exprNode, lParen, patterns, commas, rParen)
}

func createTuplePattern(pattern: ASTFormat_Pattern): TuplePattern {
    var tuplePattern = match (pattern.GetPatternAsTuplePattern()) {
        case Some(v) => v
        case None => throw ParseASTException("Failed to get the tuple pattern.")
    }
    var lParen: Token = Token(TokenKind.LPAREN).addPosition(tuplePattern.GetLeftParenPos())
    let patSrc = tuplePattern.GetPatterns()
    var patterns: ArrayList<Pattern> = ArrayList<Pattern>(patSrc.size, {i => generatePatternAST(patSrc[i])})
    let commas = Tokens()
    for (commaPos in tuplePattern.GetCommaPosVec()) {
        commas.append(Token(TokenKind.COMMA).addPosition(commaPos))
    }
    var rParen: Token = Token(TokenKind.RPAREN).addPosition(tuplePattern.GetRightParenPos())
    return TuplePattern(lParen, patterns, commas, rParen)
}
