#!/usr/bin/env python3
"""Generate the AOT compiler layout contract from compiled runtime assertions.

Run --write after an intentional ABI change; otherwise verify the checked-in
header, or --header PATH to check a compiler's copy. This checks synchronization,
not C++ layout: building runtime is required to validate the assertions.
"""
import argparse
from pathlib import Path
import re
import sys

SOURCES = (
    'CJThread/src/runtime/schedule/include/inner/cjthread.h',
    'Sync/Sync.cpp',
    'Common/BaseObject.h',
    'Common/StackType.h',
    'ObjectModel/MArray.inline.h',
    'ObjectModel/MClass.cpp',
    'ObjectModel/MFuncdesc.inline.h',
)
ASSERTION = re.compile(
    r'static_assert\(\s*(?:offsetof\(\w+,\s*\w+\)|sizeof\(\w+\)|\w+)'
    r'\s*==\s*(0x[0-9a-fA-F]+|[0-9]+),\s*'
    r'"compiler (layout|TypeInfo field) (\w+)"\s*\);')


def generate(root):
    constants = []
    fields = []
    names = set()
    for name in SOURCES:
        source = (root / 'src' / name).read_text()
        matches = list(ASSERTION.finditer(source))
        # A malformed assertion must not silently disappear from the ABI.
        if len(matches) != source.count('"compiler layout ') + source.count('"compiler TypeInfo field '):
            raise ValueError(f'{name}: unrecognized compiler layout assertion')
        for match in matches:
            value, kind, symbol = match.groups()
            if symbol in names:
                raise ValueError(f'duplicate layout assertion: {symbol}')
            names.add(symbol)
            if kind == 'TypeInfo field':
                fields.append((symbol, int(value, 0)))
            else:
                constants.append((symbol, int(value, 0)))
    if not constants or not fields:
        raise ValueError('missing runtime layout assertions')
    fields.sort(key=lambda field: field[1])
    if len({offset for _, offset in fields}) != len(fields):
        raise ValueError('overlapping TypeInfo field offsets')
    lines = [
        '// Generated by runtime/tools/generate-runtime-layout.py; do not edit.',
        '// Source of truth: runtime static_asserts; runtime must also build.',
        '// TypeInfo offsets describe the 64-bit ABI. Thread offsets are target-specific.',
        '#ifndef CANGJIE_RUNTIME_LAYOUT_H', '#define CANGJIE_RUNTIME_LAYOUT_H',
        'namespace CangjieRuntimeLayout {',
    ]
    for name, value in constants:
        lines.append(f'constexpr unsigned {name} = {value};')
    lines.append('namespace TypeInfo {')
    for index, (name, offset) in enumerate(fields):
        lines.append(f'constexpr unsigned {name}Index = {index};')
        lines.append(f'constexpr unsigned {name}Offset = {offset};')
    lines.extend(['} // namespace TypeInfo', '} // namespace CangjieRuntimeLayout', '#endif', ''])
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--runtime', type=Path, default=Path(__file__).resolve().parents[1],
                        help='runtime directory (containing src/)')
    parser.add_argument('--header', type=Path, help='header to generate or verify')
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    header = args.header or args.runtime / 'include/CangjieRuntimeLayout.h'
    expected = generate(args.runtime)
    if args.write:
        header.write_text(expected)
    elif header.read_text() != expected:
        raise ValueError(f'{header}: differs from runtime assertions; regenerate with --write')
    print(f'RUNTIME_LAYOUT {"generated" if args.write else "checked"}: {header}')


if __name__ == '__main__':
    try:
        main()
    except (OSError, ValueError) as error:
        print(f'RUNTIME_LAYOUT_ERROR: {error}', file=sys.stderr)
        sys.exit(1)
