#!/usr/bin/env python3
"""Exercise the real stdlib configure with the selected Xcode SDK (macOS)."""
import argparse
import concurrent.futures
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import time

parser = argparse.ArgumentParser()
parser.add_argument('--tuple', choices=['arm64', 'simulator_arm64', 'simulator_x86_64'], required=True)
parser.add_argument('--output', type=Path, required=True)
parser.add_argument('--baseline', required=True)
args = parser.parse_args()
repo = Path(__file__).resolve().parents[2]
output = args.output.resolve()
output.mkdir(parents=True, exist_ok=True)
sdk_name = 'iphonesimulator' if 'simulator' in args.tuple else 'iphoneos'
sdk = subprocess.check_output(['xcrun', '--sdk', sdk_name, '--show-sdk-path'], text=True).strip()
toolchain = f'ios_{args.tuple}_toolchain.cmake'
old = subprocess.check_output(['git', 'show', f'{args.baseline}:stdlib/cmake/{toolchain}'], cwd=repo)
print(f'PROBE tuple={args.tuple} sdk={sdk}', flush=True)


def run(arm):
    start = time.monotonic()
    root = output / arm
    source = root / 'stdlib'
    shutil.copytree(repo / 'stdlib', source)
    product = source / 'cmake' / toolchain
    if arm in ('baseline', 'cut'):
        # Restore the actual pre-fix toolchain, including its SDK consumer.
        product.write_bytes(old)
    digest = hashlib.sha256(product.read_bytes()).hexdigest()
    command = ['cmake', '-S', str(source), '-B', str(root / 'build'), '-G', 'Ninja',
               f'-DCMAKE_TOOLCHAIN_FILE={product}', '-DCMAKE_BUILD_TYPE=Release',
               '-DCANGJIE_SKIP_FIND_OPENSSL=ON', '-DCMAKE_POLICY_VERSION_MINIMUM=3.5',
               '-DCMAKE_C_COMPILER=clang', '-DCMAKE_CXX_COMPILER=clang++',
               '-DCMAKE_C_COMPILER_LAUNCHER=sccache', '-DCMAKE_CXX_COMPILER_LAUNCHER=sccache']
    variables = {'caller': 'CMAKE_OSX_SYSROOT', 'target': 'CANGJIE_TARGET_SYSROOT',
                 'legacy': 'CMAKE_IOS_SDK_ROOT'}
    if arm in variables:
        # Copy the real SDK to a path with spaces to distinguish caller selection
        # from automatic xcrun fallback, without replacing compiler executables.
        supplied = root / 'Caller SDK' / Path(sdk).name
        shutil.copytree(sdk, supplied, symlinks=False)
        expected = str(supplied)
        command.append(f'-D{variables[arm]}={expected}')
    else:
        expected = sdk
    with (root / 'configure.log').open('w') as log:
        log.write(json.dumps(command) + '\n')
        log.flush()
        result = subprocess.run(command, stdout=log, stderr=subprocess.STDOUT)
    # Observe compiler commands generated by the product configure, not a model.
    commands_file = root / 'build/compile_commands.json'
    commands = json.loads(commands_file.read_text()) if commands_file.exists() else []
    native = [c['command'] for c in commands if ' -c ' in c['command']]
    observed = bool(native) and all(expected in c for c in native)
    pcre_cache = root / 'build/third_party/pcre2-build/CMakeCache.txt'
    nested_sdk = pcre_cache.exists() and expected in pcre_cache.read_text()
    observed = observed and nested_sdk
    red = arm in ('baseline', 'cut')
    log_text = (root / 'configure.log').read_text()
    precise_red = result.returncode != 0 and '17.5.sdk' in log_text and 'Ignoring CMAKE_OSX_SYSROOT value' in log_text and "library 'System' not found" in log_text
    passed = precise_red if red else result.returncode == 0 and observed
    record = dict(arm=arm, tuple=args.tuple, rc=result.returncode, sdk=expected,
                  product_sha256=digest, configure_command=command,
                  native_commands=len(native), sdk_assertion=observed,
                  precise_red=precise_red, passed=passed, wall=time.monotonic()-start)
    (root / 'result.json').write_text(json.dumps(record, indent=2) + '\n')
    print(json.dumps(record), flush=True)
    return record


# Independent source/build directories; all arms use the same dependency sources.
arms = ['baseline', 'candidate', 'cut', 'restored', 'caller', 'target', 'legacy']
with concurrent.futures.ThreadPoolExecutor(max_workers=len(arms)) as pool:
    results = list(pool.map(run, arms))
by_arm = {r['arm']: r for r in results}
assert by_arm['candidate']['product_sha256'] == by_arm['restored']['product_sha256']
assert by_arm['candidate']['product_sha256'] != by_arm['cut']['product_sha256']
(output / 'results.json').write_text(json.dumps(results, indent=2) + '\n')
raise SystemExit(0 if all(r['passed'] for r in results) else 1)
